version: '3'

services:
  lxsky-core:
      build:
        dockerfile: dev.dockerfile
      ports: 
        - 13000:3000
      volumes:
        - ./core:/core
        - /core/node_modules
      env_file:
        - .dev.env