version: '3'

services:
  lxsky-mysql:
    image: ${CR_LOCATION}/lxsky-mysql:${IMG_TAG}
    build: 
      context: .
      dockerfile: maria.dockerfile
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_SQL_PASSWORD}
      - MARIADB_DATABASE=${DB_SQL_APP_DB}

  lxsky-redis:
    image: ${CR_LOCATION}/lxsky-redis:${IMG_TAG}
    build: 
      context: .
      dockerfile: redis.dockerfile
  
  lxsky-core:
    image: ${CR_LOCATION}/lxsky-core:${IMG_TAG}
    build:
      context: core/
      dockerfile: dockerfile
    depends_on:
      - lxsky-mysql
      - lxsky-redis
    env_file:
      - .env

  lxsky-frontend:
    image: ${CR_LOCATION}/lxsky-frontend:${IMG_TAG}
    build: 
      context: front/public
      dockerfile: dockerfile
