// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddChild: typeof import('./src/components/icons/AddChild.vue')['default']
    'AddChild copy': typeof import('./src/components/icons/AddChild copy.vue')['default']
    AddChildren: typeof import('./src/components/icons/AddChildren.vue')['default']
    AddDocument: typeof import('./src/components/icons/AddDocument.vue')['default']
    AddParent: typeof import('./src/components/icons/AddParent.vue')['default']
    AddSibling: typeof import('./src/components/icons/AddSibling.vue')['default']
    ArticleControlPanel: typeof import('./src/components/admin/ArticleControlPanel.vue')['default']
    ArticleDisplay: typeof import('./src/components/ArticleDisplay.vue')['default']
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    ArticleListEntry: typeof import('./src/components/ArticleListEntry.vue')['default']
    AsyncContent: typeof import('./src/components/AsyncContent.vue')['default']
    CategoryControlPanel: typeof import('./src/components/admin/CategoryControlPanel.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    CategoryListEntry: typeof import('./src/components/CategoryListEntry.vue')['default']
    DynamicArticleList: typeof import('./src/components/DynamicArticleList.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    LunaCuiteMark: typeof import('./src/components/LunaCutieMark.vue')['default']
    LunaCutieMark: typeof import('./src/components/LunaCutieMark.vue')['default']
    NotificationItem: typeof import('./src/components/NotificationItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteLogo: typeof import('./src/components/SiteLogo.vue')['default']
    StackableNotifications: typeof import('./src/components/StackableNotifications.vue')['default']
    TwilightCutieMark: typeof import('./src/components/TwilightCutieMark.vue')['default']
    UploadArticlePopup: typeof import('./src/components/admin/UploadArticlePopup.vue')['default']
  }
}

export {}
