name: Deployment
on:
  push:
    branches: main
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitLab Registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}
      -
        name: Exporting build environment
        run: printf "${{ secrets.BUILD_ENV }}" > .env && cat .env && exit 1
      -
        name: Build and push Containers
        run: chmod +x ./run.sh && sudo ./run.sh build
      -
        name: Generate stack file
        run: docker compose -f docker-compose.yaml -f prod.docker-compose.yaml convert > stack.yaml
      - 
        name: Deploy to Docker Swarm
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: swarm@ssh.lunaixsky.com
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          stack_file_name: stack.yaml
